"use strict";

exports.Customer = require("./Customer");
exports.ResetPassword = require("./ResetPassword");
exports.Country = require("./Country");
exports.City = require("./City");
exports.State = require("./State");
exports.Area = require("./Area");
exports.Otp = require("./Otp");
exports.ReferralCode = require("./ReferralCode");
exports.FAQ = require("./FAQ");
exports.InstrumentCategory = require("./InstrumentCategory");
exports.Ticket = require("./Ticket");
exports.Notification = require("./Notification");
exports.Rating = require("./Rating");
exports.Slider = require("./Slider");
exports.Order = require("./Order");
exports.User = require("./User");
exports.PushNotification = require("./PushNotification");
exports.Settings = require("./Settings");
exports.Product = require("./Product");
exports.Manufacturer = require("./Manufacturer");
exports.Review = require("./Review");
exports.NewsEvent = require("./NewsEvent");
exports.Bundle = require("./Bundle");
